// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';

export function ApplyProfile(arg1:string):Promise<void>;

export function CreateSnapshot(arg1:string):Promise<backend.Snapshot>;

export function DeactivateProfile(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteSnapshot(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function GetConfigPath():Promise<string>;

export function GetDisabledPaths():Promise<Array<string>>;

export function GetPresets():Promise<Array<backend.Template>>;

export function GetProfiles():Promise<Array<backend.Profile>>;

export function GetSnapshots():Promise<Array<backend.Snapshot>>;

export function GetTemplates():Promise<Array<backend.Template>>;

export function RestoreSnapshot(arg1:string):Promise<void>;

export function SaveProfile(arg1:backend.Profile):Promise<void>;

export function SaveTemplate(arg1:backend.Template):Promise<void>;

export function SetDisabledPaths(arg1:Array<string>):Promise<void>;
