// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyProfile(arg1) {
  return window['go']['backend']['DataManager']['ApplyProfile'](arg1);
}

export function CreateSnapshot(arg1) {
  return window['go']['backend']['DataManager']['CreateSnapshot'](arg1);
}

export function DeactivateProfile(arg1) {
  return window['go']['backend']['DataManager']['DeactivateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['backend']['DataManager']['DeleteProfile'](arg1);
}

export function DeleteSnapshot(arg1) {
  return window['go']['backend']['DataManager']['DeleteSnapshot'](arg1);
}

export function DeleteTemplate(arg1) {
  return window['go']['backend']['DataManager']['DeleteTemplate'](arg1);
}

export function GetConfigPath() {
  return window['go']['backend']['DataManager']['GetConfigPath']();
}

export function GetDisabledPaths() {
  return window['go']['backend']['DataManager']['GetDisabledPaths']();
}

export function GetPresets() {
  return window['go']['backend']['DataManager']['GetPresets']();
}

export function GetProfiles() {
  return window['go']['backend']['DataManager']['GetProfiles']();
}

export function GetSnapshots() {
  return window['go']['backend']['DataManager']['GetSnapshots']();
}

export function GetTemplates() {
  return window['go']['backend']['DataManager']['GetTemplates']();
}

export function RestoreSnapshot(arg1) {
  return window['go']['backend']['DataManager']['RestoreSnapshot'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['backend']['DataManager']['SaveProfile'](arg1);
}

export function SaveTemplate(arg1) {
  return window['go']['backend']['DataManager']['SaveTemplate'](arg1);
}

export function SetDisabledPaths(arg1) {
  return window['go']['backend']['DataManager']['SetDisabledPaths'](arg1);
}
