// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {frontend} from '../models';

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog(arg1:Array<frontend.FileFilter>):Promise<string>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function ReadFileContent(arg1:string):Promise<string>;

export function SaveFileDialog(arg1:string,arg2:Array<frontend.FileFilter>):Promise<string>;

export function SelectDirectory():Promise<string>;

export function WriteFileContent(arg1:string,arg2:string):Promise<void>;
